name: Build & Push Remix Weather Docker Image

on:
  pull_request:
    paths:
      - 'app/**'
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: veka0011acr.azurecr.io

      - name: Build and Push Docker Image
        run: |
          docker build -t veka0011acr.azurecr.io/remix-weather:${{ github.sha }} .
          docker push veka0011acr.azurecr.io/remix-weather:${{ github.sha }}

      - name: Save Image Tag Output
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
