name: Terraform Plan (Pull Request)

on:
  pull_request:
    branches: [main]

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Init
        run: terraform init

      - name: TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Terraform Plan
        run: terraform plan -var-file="infrastructure/environments/test/terraform.tfvars"
